### ISSUE TITLE
Issue compiling Atomicbird + RemoteViewing 

### ISSUE THREAD

**Issue by NotoriousRebel** [FuzzySecurity/Sharp-Suite#3]
I cloned the repo and tried to build AtomicBird and RemoteViewing and got the same error for both:
The weird thing is that these projects use to build for me just fine but not anymore :/ 
```1>------ Build started: Project: RemoteViewing, Configuration: Debug x64 ------
1>    Fody: Fody (version 2.5.0.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>MSBUILD : error : Type:
1>MSBUILD : error : System.IO.FileLoadException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver..ctor()
1>MSBUILD : error :    at lambda_method(Closure )
1>MSBUILD : error :    at InnerWeaver.InitialiseWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 146
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 100
1>MSBUILD : error : Source:
1>MSBUILD : error : Costura.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void .ctor()
1>MSBUILD : error : 
1>    Fody:   Finished Fody 21ms.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by FuzzySecurity** [comment]
Did you manage to figure this out? I can't repro this issue. Try clearing your nuget cache.

```
1>------ Rebuild All started: Project: AtomicBird, Configuration: Release x64 ------
1>    Fody: Fody (version 2.5.0.0) Executing
1>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
1>      Fody/Costura:   	Embedding 'C:\Users\b33f\.nuget\packages\easyhook\2.7.7097\lib\net35\EasyHook.dll'
1>      Fody/Costura:   	Embedding 'C:\Users\b33f\.nuget\packages\easyhook\2.7.7097\contentFiles\any\net35\EasyHook32.dll'
1>      Fody/Costura:   	Embedding 'C:\Users\b33f\.nuget\packages\easyhook\2.7.7097\contentFiles\any\net35\EasyHook64.dll'
1>    Fody:   Finished Fody 788ms.
1>  AtomicBird -> C:\Users\b33f\Desktop\AtomicBird\bin\x64\Release\AtomicBird.exe
1>    Fody:   Skipped Verifying assembly since it is disabled in configuration
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by NotoriousRebel** [comment]
Yes clearing the cache has solved that problem! Thank you
